//급여제도 SALARY
export const SALARY_BENEFITS = {
  SALARY_RETIREMENT_PENSION: '퇴직연금',
  SALARY_INCENTIVE: '인센티브제',
  SALARY_BONUS: '상여금',
  SALARY_LONG_TERM_RECOGNITION: '장기근속자 포상',
  SALARY_PERFORMANCE_BONUS: '성과급',
  SALARY_SEVERANCE_PAY: '퇴직금',
  SALARY_EMPLOYEE_AWARD: '우수사원포상',
  // SALARY_STOCK_OPTION: '스톡옵션',
  SALARY_NIGHT_ALLOWANCE: '야근수당',
  SALARY_HOLIDAY_ALLOWANCE: '휴일(특근)수당',
  SALARY_ANNUAL_ALLOWANCE: '연차수당',
  SALARY_POSITION_ALLOWANCE: '직책수당',
  SALARY_CERTIFICATION_ALLOWANCE: '자격증수당',
  SALARY_LONG_TERM_ALLOWANCE: '장기근속수당',
  SALARY_RISK_ALLOWANCE: '위험수당',
  // SALARY_FAMILY_ALLOWANCE: '가족수당',
  SALARY_SOCIAL_INSURANCE: '4대 보험',
};

//조직문화 CULTURE
export const CULTURE_BENEFITS = {
  // CULTURE_UNLIMITED_ANNUAL_LEAVE: '무제한 연차',
  // CULTURE_LABOR_UNION: '노조/노사협의회',
  CULTURE_FLAT_ORGANIZATION: '수평적 조직문화',
  CULTURE_NO_COMPULSORY_MEALS: '회식강요 안함',
  CULTURE_NIGHT_SHIFT_OPT_OUT: '야근강요 안함',
  // CULTURE_CASUAL_DAY: '캐주얼데이',
  CULTURE_FREE_DRESS_CODE: '자유복장',
  // CULTURE_FLEXIBLE_ANNUAL_LEAVE: '자유로운 연차사용',
  // CULTURE_PET_FRIENDLY_OFFICE: '반려동물 동반출근',
  // CULTURE_HONORIFIC_CULTURE: '님/닉네임 문화',
  // CULTURE_MATERNITY_AND_PATERNITY_BENEFITS: '출산 장려',
  CULTURE_CULTURAL_MEETINGS: '문화 회식',
  // CULTURE_INTERNAL_CELEBRATIONS: '사내연애 장려',
  CULTURE_GUARANTEED_RETIREMENT: '칼퇴근 보장',
};

//선물 GIFTS
export const GIFTS_BENEFITS = {
  GIFTS_HOLIDAY_GIFT_OR_EXPENSES: '명절선물/귀향비',
  GIFTS_FOUNDATION_GIFT: '창립일선물지급',
  GIFTS_BIRTHDAY_GIFT_PARTY: '생일선물/파티',
  GIFTS_CHRISTMAS_GIFT: '크리스마스 선물',
  GIFTS_WEDDING_GIFT: '결혼기념일선물',
  // GIFTS_UNLIMITED_BOOKS: '도서 무제한 제공',
  GIFTS_MATERNITY_GIFT: '임신/출산 선물',
  // GIFTS_WELCOME_KIT: '웰컴키트 지급',
  GIFTS_BIRTHDAY_EARLY_LEAVE: '생일자 조기퇴근',
  GIFTS_LONG_SERVICE_GIFT: '장기근속 선물',
};

//출퇴근 WORK_LIFE
export const WORK_LIFE_BENEFITS = {
  WORK_LIFE_DORMITORY_OPERATION: '숙식 제공',
  WORK_LIFE_VEHICLE_FUEL_SUPPORT: '차량유류비지원',
  WORK_LIFE_COMMUTER_BUS: '통근버스 운영',
  WORK_LIFE_HOUSING_PROVISION: '사택제공',
  // WORK_LIFE_STAFF_APARTMENT: '사원아파트 임대',
  WORK_LIFE_HOUSING_LOAN: '주택자금 융자',
  WORK_LIFE_NIGHT_COMMUTE_ALLOWANCE: '야간교통비지급',
  WORK_LIFE_COMPANY_VEHICLE: '회사차량 있음',
  WORK_LIFE_PARKING_SUPPORT: '주차장제공',
  WORK_LIFE_RENT_SUPPORT: '주차비지원',
  WORK_LIFE_HOUSING_ALLOWANCE: '주거비 지원',
  // WORK_LIFE_RENTAL_DEPOSIT_LOAN: '전세자금 대출',
  WORK_LIFE_COMMUTE_SUPPORT: '출퇴근 교통비 지원',
  // WORK_LIFE_FLEXIBLE_WORK: '탄력근무제',
  // WORK_LIFE_REMOTE_WORK: '재택근무',
  // WORK_LIFE_WEEK_40_HOURS: '주 40시간제 시행',
  // WORK_LIFE_WEEK_52_HOURS: '주 52시간제 준수',
  // WORK_LIFE_FOUR_AND_HALF_DAY: '주4.5일',
  // WORK_LIFE_FOUR_DAY: '주4일',
  // WORK_LIFE_SELF_DIRECTED_WORK: '자율 근무제',
};

// 지원금/보험 SUPPORT_HEALTH
export const SUPPORT_HEATH_BENEFITS = {
  SUPPORT_HEALTH_HEALTH_CHECKUP: '건강검진',
  SUPPORT_HEALTH_MEDICAL_SUPPORT_SELF: '의료비지원(본인)',
  SUPPORT_HEALTH_MEDICAL_SUPPORT_FAMILY: '의료비지원(가족)',
  SUPPORT_HEALTH_SMOKING_CESSATION: '금연수당',
  SUPPORT_HEALTH_EMPLOYEE_LOAN: '직원대출제도',
  SUPPORT_HEALTH_GROUP_INSURANCE: '단체 상해보험',
  SUPPORT_HEALTH_FITNESS_CENTER: '체력단련실운영',
  // SUPPORT_HEALTH_EDUCATION_SUPPORT_SELF: '본인학자금',
  SUPPORT_HEALTH_WEDDING_PREPARATION: '결혼준비 지원',
  // SUPPORT_HEALTH_ABROAD_TRAVEL_SUPPORT: '해외여행 지원',
  // SUPPORT_HEALTH_ACTIVITY_EXPENSE: '업무활동비 지급',
  // SUPPORT_HEALTH_INFERTILITY_TREATMENT: '난임 치료 지원',
  SUPPORT_HEALTH_DISCOUNT_PRODUCTS: '주요 제품 직원 할인',
  SUPPORT_HEALTH_CULTURAL_ACTIVITY: '문화생활비',
  SUPPORT_HEALTH_COMMUNICATION_SUPPORT: '통신비 지원',
  SUPPORT_HEALTH_WELFARE_CARD_POINTS: '복지카드/포인트',
  SUPPORT_HEALTH_INTERNAL_WEDDING_HALL: '사내 결혼식장 제공',
  SUPPORT_HEALTH_SCHOLARSHIP_CHILDREN: '자녀학자금',
  SUPPORT_HEALTH_SUBSIDY_FOR_SURVEY: '각종 경조사 지원',
  SUPPORT_HEALTH_HEALTH_SUBSIDY: '헬스비 지급',
  SUPPORT_HEALTH_FREE_MEDICAL: '무료진료지정병원',
  SUPPORT_HEALTH_SELECTIVE_WELFARE: '선택적복리후생',
  SUPPORT_HEALTH_INTERNAL_RECRUITMENT: '내일채움공제',
};

//리프레시 REFRESH
export const REFRESH_BENEFITS = {
  REFRESH_ANNUAL_LEAVE: '연차',
  REFRESH_SUMMER_LEAVE: '여름휴가',
  REFRESH_FAMILY_EVENT_LEAVE: '경조휴가제',
  REFRESH_HALF_DAY_LEAVE: '반차',
  REFRESH_REFRESH_LEAVE: 'Refresh휴가',
  REFRESH_FOUNDATION_DAY_LEAVE: '창립일휴무',
  REFRESH_LABOR_DAY_LEAVE: '근로자의 날 휴무',
  REFRESH_LEAVE_ALLOWANCE: '휴가비지원',
  REFRESH_AWARD_LEAVE: '포상휴가',
  REFRESH_MATERNITY_LEAVE: '산전 후 휴가',
  REFRESH_PARENTAL_LEAVE: '육아휴직',
  REFRESH_PATERNITY_LEAVE: '남성출산휴가',
  REFRESH_SICK_LEAVE: '보건휴가',
  REFRESH_HOLIDAY_FACILITY: '휴양시설 제공',
  REFRESH_FAMILY_DAY: '패밀리데이',
  REFRESH_TIME_OFF_EXTENSION: '시간제 연차',
  REFRESH_PUBLIC_HOLIDAY_LEAVE: '공휴일 휴무',
};

export const BENEFITS = {
  ...CULTURE_BENEFITS,
  ...SALARY_BENEFITS,
  ...GIFTS_BENEFITS,
  ...REFRESH_BENEFITS,
  ...SUPPORT_HEATH_BENEFITS,
  ...WORK_LIFE_BENEFITS,
};
