export const LOCATION = {
  서울: {
    강남구: 'seoul.gangnam-gu',
    강동구: 'seoul.gangdong-gu',
    강북구: 'seoul.gangbuk-gu',
    강서구: 'seoul.gangseo-gu',
    관악구: 'seoul.gwanak-gu',
    광진구: 'seoul.gwangjin-gu',
    구로구: 'seoul.guro-gu',
    금천구: 'seoul.geumcheon-gu',
    노원구: 'seoul.nowon-gu',
    도봉구: 'seoul.dobong-gu',
    동대문구: 'seoul.dongdaemun-gu',
    동작구: 'seoul.dongjak-gu',
    마포구: 'seoul.mapo-gu',
    서대문구: 'seoul.seodaemun-gu',
    서초구: 'seoul.seocho-gu',
    성동구: 'seoul.seongdong-gu',
    성북구: 'seoul.seongbuk-gu',
    송파구: 'seoul.songpa-gu',
    양천구: 'seoul.yangcheon-gu',
    영등포구: 'seoul.yeongdeungpo-gu',
    용산구: 'seoul.yongsan-gu',
    은평구: 'seoul.eunpyeong-gu',
    종로구: 'seoul.jongno-gu',
    중구: 'seoul.jung-gu',
    중랑구: 'seoul.jungnang-gu',
  },
  경기: {
    수원시: 'gyeonggi.suwon-si',
    성남시: 'gyeonggi.seongnam-si',
    고양시: 'gyeonggi.goyang-si',
    용인시: 'gyeonggi.yongin-si',
    부천시: 'gyeonggi.bucheon-si',
    안산시: 'gyeonggi.ansan-si',
    안양시: 'gyeonggi.anyang-si',
    남양주시: 'gyeonggi.namyangju-si',
    화성시: 'gyeonggi.hwaseong-si',
    평택시: 'gyeonggi.pyeongtaek-si',
    의정부시: 'gyeonggi.uiijeongbu-si',
    파주시: 'gyeonggi.paju-si',
    시흥시: 'gyeonggi.siheung-si',
    광명시: 'gyeonggi.gwangmyeong-si',
    김포시: 'gyeonggi.gimpo-si',
    군포시: 'gyeonggi.gunpo-si',
    광주시: 'gyeonggi.gwangju-si',
    이천시: 'gyeonggi.icheon-si',
    양주시: 'gyeonggi.yangju-si',
    구리시: 'gyeonggi.guri-si',
    오산시: 'gyeonggi.osan-si',
    안성시: 'gyeonggi.anseong-si',
    포천시: 'gyeonggi.pocheon-si',
    의왕시: 'gyeonggi.uiwang-si',
    하남시: 'gyeonggi.hanam-si',
    여주시: 'gyeonggi.yeoju-si',
    양평군: 'gyeonggi.yangpyeong-gun',
    과천시: 'gyeonggi.gwacheon-si',
    가평군: 'gyeonggi.gapyeong-gun',
    연천군: 'gyeonggi.yeoncheon-gun',
  },
  부산: {
    강서구: 'busan.gangseo-gu',
    금정구: 'busan.geumjeong-gu',
    남구: 'busan.nam-gu',
    동구: 'busan.dong-gu',
    동래구: 'busan.dongnae-gu',
    부산진구: 'busan.busanjin-gu',
    북구: 'busan.buk-gu',
    사상구: 'busan.sasang-gu',
    사하구: 'busan.saha-gu',
    서구: 'busan.seo-gu',
    수영구: 'busan.suyeong-gu',
    연제구: 'busan.yeonje-gu',
    영도구: 'busan.yeongdo-gu',
    중구: 'busan.jung-gu',
    해운대구: 'busan.haeundae-gu',
  },
  강원: {
    춘천시: 'gangwon.chuncheon-si',
    원주시: 'gangwon.wonju-si',
    강릉시: 'gangwon.gangneung-si',
    동해시: 'gangwon.donghae-si',
    태백시: 'gangwon.taebaek-si',
    속초시: 'gangwon.sokcho-si',
    삼척시: 'gangwon.samcheok-si',
    홍천군: 'gangwon.hongcheon-gun',
    횡성군: 'gangwon.hoengseong-gun',
    영월군: 'gangwon.yeongwol-gun',
    평창군: 'gangwon.pyeongchang-gun',
    정선군: 'gangwon.jeongseon-gun',
    철원군: 'gangwon.cheorwon-gun',
    화천군: 'gangwon.hwachon-gun',
    양구군: 'gangwon.yanggu-gun',
    인제군: 'gangwon.inje-gun',
    고성군: 'gangwon.goseong-gun',
    양양군: 'gangwon.yangyang-gun',
  },
  경남: {
    창원시: 'gyeongnam.changwon-si',
    김해시: 'gyeongnam.gimhae-si',
    진주시: 'gyeongnam.jinju-si',
    양산시: 'gyeongnam.yangsan-si',
    거제시: 'gyeongnam.geoje-si',
    통영시: 'gyeongnam.tongyeong-si',
    사천시: 'gyeongnam.sacheon-si',
    밀양시: 'gyeongnam.miryang-si',
    함안군: 'gyeongnam.haman-gun',
    거창군: 'gyeongnam.geochang-gun',
    창녕군: 'gyeongnam.changnyeong-gun',
    고성군: 'gyeongnam.goseong-gun',
    남해군: 'gyeongnam.namhae-gun',
    하동군: 'gyeongnam.hadong-gun',
    산청군: 'gyeongnam.sancheong-gun',
    함양군: 'gyeongnam.hamyang-gun',
    합천군: 'gyeongnam.hapcheon-gun',
  },
  경북: {
    포항시: 'gyeongbuk.pohang-si',
    경주시: 'gyeongbuk.gyeongju-si',
    김천시: 'gyeongbuk.gimcheon-si',
    안동시: 'gyeongbuk.andong-si',
    구미시: 'gyeongbuk.gumi-si',
    영주시: 'gyeongbuk.yeongju-si',
    영천시: 'gyeongbuk.yeongcheon-si',
    상주시: 'gyeongbuk.sangju-si',
    문경시: 'gyeongbuk.mungyeong-si',
    경산시: 'gyeongbuk.gyeongsan-si',
    군위군: 'gyeongbuk.gunwi-gun',
    의성군: 'gyeongbuk.uisung-gun',
    청송군: 'gyeongbuk.cheongsong-gun',
    영양군: 'gyeongbuk.youngyang-gun',
    영덕군: 'gyeongbuk.yeongdeok-gun',
    청도군: 'gyeongbuk.cheongdo-gun',
    고령군: 'gyeongbuk.goryeong-gun',
    성주군: 'gyeongbuk.seongju-gun',
    칠곡군: 'gyeongbuk.chilgok-gun',
    예천군: 'gyeongbuk.yecheon-gun',
    봉화군: 'gyeongbuk.bonghwa-gun',
    울진군: 'gyeongbuk.uljin-gun',
    울릉군: 'gyeongbuk.ulreung-gun',
  },
  광주: {
    동구: 'gwangju.dong-gu',
    서구: 'gwangju.seo-gu',
    남구: 'gwangju.nam-gu',
    북구: 'gwangju.buk-gu',
    광산구: 'gwangju.gwangsan-gu',
  },
  대구: {
    중구: 'daegu.jung-gu',
    동구: 'daegu.dong-gu',
    서구: 'daegu.seo-gu',
    남구: 'daegu.nam-gu',
    북구: 'daegu.buk-gu',
    수성구: 'daegu.suseong-gu',
    달서구: 'daegu.dalseo-gu',
    달성군: 'daegu.dalseong-gun',
  },
  대전: {
    동구: 'daejeon.dong-gu',
    중구: 'daejeon.jung-gu',
    서구: 'daejeon.seo-gu',
    유성구: 'daejeon.yuseong-gu',
    대덕구: 'daejeon.daedeok-gu',
  },
  세종: {
    조치원읍: 'sejong.jochiwon-eup',
    연기면: 'sejong.yeongi-myeon',
    연동면: 'sejong.yeondong-myeon',
    부강면: 'sejong.bugang-myeon',
    금남면: 'sejong.geumnam-myeon',
    장군면: 'sejong.janggun-myeon',
    연서면: 'sejong.yeonseo-myeon',
    전의면: 'sejong.jeonui-myeon',
    전동면: 'sejong.jeondong-myeon',
    소정면: 'sejong.sojeong-myeon',
    한솔동: 'sejong.hansol-dong',
    도담동: 'sejong.dodam-dong',
    아름동: 'sejong.areum-dong',
    종촌동: 'sejong.jongchon-dong',
    고운동: 'sejong.goun-dong',
    소담동: 'sejong.sodam-dong',
    반곡동: 'sejong.bangok-dong',
    보람동: 'sejong.boram-dong',
    대평동: 'sejong.daepyeong-dong',
    다정동: 'sejong.dajeong-dong',
  },
  울산: {
    중구: 'ulsan.jung-gu',
    남구: 'ulsan.nam-gu',
    동구: 'ulsan.dong-gu',
    북구: 'ulsan.buk-gu',
    울주군: 'ulsan.ulju-gun',
  },
  인천: {
    중구: 'incheon.jung-gu',
    동구: 'incheon.dong-gu',
    미추홀구: 'incheon.michuhol-gu',
    연수구: 'incheon.yeonsu-gu',
    남동구: 'incheon.namdong-gu',
    부평구: 'incheon.bupyeong-gu',
    계양구: 'incheon.gyeyang-gu',
    서구: 'incheon.seo-gu',
    강화군: 'incheon.ganghwa-gun',
    옹진군: 'incheon.ongjin-gun',
  },
  전남: {
    목포시: 'jeonnam.mokpo-si',
    여수시: 'jeonnam.yeosu-si',
    순천시: 'jeonnam.suncheon-si',
    나주시: 'jeonnam.naju-si',
    광양시: 'jeonnam.gwangyang-si',
    담양군: 'jeonnam.damyang-gun',
    곡성군: 'jeonnam.gokseong-gun',
    구례군: 'jeonnam.gurye-gun',
    고흥군: 'jeonnam.goheung-gun',
    보성군: 'jeonnam.boseong-gun',
    화순군: 'jeonnam.hwasun-gun',
    장흥군: 'jeonnam.jangheung-gun',
    강진군: 'jeonnam.gangjin-gun',
    해남군: 'jeonnam.haenam-gun',
    영암군: 'jeonnam.yeongam-gun',
    무안군: 'jeonnam.muan-gun',
    함평군: 'jeonnam.hampyeong-gun',
    영광군: 'jeonnam.yeonggwang-gun',
    장성군: 'jeonnam.jangseong-gun',
    완도군: 'jeonnam.wando-gun',
    진도군: 'jeonnam.jindo-gun',
    신안군: 'jeonnam.shinan-gun',
  },
  전북: {
    전주시: 'jeonbuk.jeonju-si',
    군산시: 'jeonbuk.gunsan-si',
    익산시: 'jeonbuk.iksan-si',
    정읍시: 'jeonbuk.jeongeup-si',
    남원시: 'jeonbuk.namwon-si',
    김제시: 'jeonbuk.gimje-si',
    완주군: 'jeonbuk.wanju-gun',
    진안군: 'jeonbuk.jinan-gun',
    무주군: 'jeonbuk.muju-gun',
    장수군: 'jeonbuk.jangsu-gun',
    임실군: 'jeonbuk.imsil-gun',
    순창군: 'jeonbuk.sunchang-gun',
    고창군: 'jeonbuk.gochang-gun',
    부안군: 'jeonbuk.buan-gun',
  },
  충남: {
    천안시: 'chungnam.cheonan-si',
    공주시: 'chungnam.gongju-si',
    보령시: 'chungnam.boryeong-si',
    아산시: 'chungnam.asan-si',
    서산시: 'chungnam.seosan-si',
    논산시: 'chungnam.nonsan-si',
    계룡시: 'chungnam.gyeryong-si',
    당진시: 'chungnam.dangjin-si',
    금산군: 'chungnam.geumsan-gun',
    부여군: 'chungnam.buyeo-gun',
    서천군: 'chungnam.seocheon-gun',
    청양군: 'chungnam.cheongyang-gun',
    홍성군: 'chungnam.hongseong-gun',
    예산군: 'chungnam.yesan-gun',
    태안군: 'chungnam.taean-gun',
  },
  충북: {
    청주시: 'chungbuk.cheongju-si',
    충주시: 'chungbuk.chungju-si',
    제천시: 'chungbuk.jecheon-si',
    보은군: 'chungbuk.boeun-gun',
    옥천군: 'chungbuk.okcheon-gun',
    영동군: 'chungbuk.yeongdong-gun',
    증평군: 'chungbuk.jeungpyeong-gun',
    진천군: 'chungbuk.jincheon-gun',
    괴산군: 'chungbuk.goesan-gun',
    음성군: 'chungbuk.eumseong-gun',
    단양군: 'chungbuk.danyang-gun',
  },
  제주: {
    제주시: 'jeju.jeju-si',
    서귀포시: 'jeju.seogwipo-si',
  },
};

export const CITY = {
  전국: 'all',
  서울: 'seoul.all',
  경기: 'gyeonggi.all',
  부산: 'busan.all',
  강원: 'gangwon.all', //강원 -> 강원특별자치도
  경남: 'gyeongnam.all',
  경북: 'gyeongbuk.all', //ok
  광주: 'gwangju.all', //
  대구: 'daegu.all',
  대전: 'daejeon.all',
  세종: 'sejong.all', //세종 -> 세종특별자치시
  울산: 'ulsan.all',
  인천: 'incheon.all',
  전남: 'jeonnam.all',
  전북: 'jeonbuk.all', //전북 -> 전북특별자치도
  충남: 'chungnam.all',
  충북: 'chungbuk.all',
  제주: 'jeju.all', //제주 -> 제주특별자치도
} as const;

export const CITY_KOREAN_MAP = {
  서울: '서울',
  경기: '경기',
  부산: '부산',
  강원특별자치도: '강원', //강원 -> 강원특별자치도
  경남: '경남',
  경북: '경북', //ok
  광주: '광주', //
  대구: '대구',
  대전: '대전',
  세종특별자치시: '세종', //세종 -> 세종특별자치시
  울산: '울산',
  인천: '인천',
  전남: '전남',
  전북특별자치도: '전북', //전북 -> 전북특별자치도',
  충북: '충북',
  제주특별자치도: '제주', //제주 -> 제주특별자치도
} as const;
