const queryKeys = {
  TALENT_LIST: 'TALENT_LIST',
  USER_INFO: 'USER_INFO',
  REFRESH_COOKIE: 'REFRESH_COOKIE',
  MY_COMPANY: 'MY_COMPANY',
  EMPLOYER_ACCOUNT: 'EMPLOYER_ACCOUNT',
  RECRUITMENT_LIST: 'RECRUITMENT_LIST',
  RECRUITMENT_DETAIL: 'RECRUITMENT_DETAIL',
  RECRUITMENT_STATUS: 'RECRUITMENT_STATUS',

  RECRUIT_SPECIAL_LIST: 'recruitSpecialList',
  RECRUIT_URGENT_LIST: 'recruitUrgentList',
  RECRUIT_BASIC_LIST: 'recruitBasicList',
};

export default queryKeys;
