const queryKeys = {
  TALENT_LIST: 'TALENT_LIST',
  USER_INFO: 'USER_INFO',
  REFRESH_COOKIE: 'REFRESH_COOKIE',
  MY_COMPANY: 'MY_COMPANY',
  EMPLOYER_ACCOUNT: 'EMPLOYER_ACCOUNT',
  RECRUITMENT_LIST: 'RECRUITMENT_LIST',
  RECRUITMENT_DETAIL: 'RECRUITMENT_DETAIL',
  RECRUITMENT_STATUS: 'RECRUITMENT_STATUS',

  RECRUIT_SPECIAL_LIST: 'RECRUIT_SPECIAL_LIST',
  RECRUIT_URGENT_LIST: 'RECRUIT_URGENT_LIST',
  RECRUIT_BASIC_LIST: 'RECRUIT_BASIC_LIST',
  RECRUIT_DETAIL: 'RECRUIT_DETAIL',

  APPLICATION_APPLY_CHECK: 'APPLICATION_APPLY_CHECK',

  RESUME_EDIT: 'RESUME_EDIT', // 이력서 수정
  RESUME_DETAIL: 'RESUME_DETAIL', // 이력서 상세
  RESUME_LIST: 'RESUME_LIST', // 이력서 리스트
  AVAILABLE_RESUME_LIST: 'AVAILABLE_RESUME_LIST', // 지원가능한 이력서 리스트
};

export default queryKeys;
