const queryKeys = {
  TALENT_LIST: 'TALENT_LIST',

  AUTH_ME: 'AUTH_ME',
  USER_PROFILE: 'USER_PROFILE',

  REFRESH_COOKIE: 'REFRESH_COOKIE',
  MY_COMPANY: 'MY_COMPANY',
  EMPLOYER_ACCOUNT: 'EMPLOYER_ACCOUNT',

  RECRUITMENT_LIST: 'RECRUITMENT_LIST',
  RECRUITMENT_DETAIL: 'RECRUITMENT_DETAIL',
  RECRUITMENT_STATUS: 'RECRUITMENT_STATUS', //채용공고 목록 상태 집계

  RECRUIT_SPECIAL_LIST: 'RECRUIT_SPECIAL_LIST',
  RECRUIT_URGENT_LIST: 'RECRUIT_URGENT_LIST',
  RECRUIT_BASIC_LIST: 'RECRUIT_BASIC_LIST',
  RECRUIT_DETAIL: 'RECRUIT_DETAIL',

  APPLICATION_APPLY_CHECK: 'APPLICATION_APPLY_CHECK',
  APPLICATION_RECRUITMENT_STATUS_COUNT: 'APPLICATION_RECRUITMENT_STATUS_COUNT',

  RESUME_EDIT: 'RESUME_EDIT', // 이력서 수정
  RESUME_DETAIL: 'RESUME_DETAIL', // 이력서 상세
  RESUME_LIST: 'RESUME_LIST', // 이력서 리스트
  AVAILABLE_RESUME_LIST: 'AVAILABLE_RESUME_LIST', // 지원가능한 이력서 리스트
  USER_APPLICATION_HISTORY: 'USER_APPLICATION_HISTORY', // 채용공고 지원내역

  PRODUCT_RECRUITMENT: 'PRODUCT_RECRUITMENT',
};

export default queryKeys;
