export const errorCode = {
  ALREADY_EXISTS: 'ERR-409',
  OAUTH_SIGN_IN_NOT_FOUND_USER: 'ERR-2002',
  OAUTH_SIGN_IN_TOKEN_RATE_LIMIT: 'ERR-2005',
  PAYMENT_NOT_FOUND_ORDER: 'ERR-4012',
  PAYMENT_EXPIRED_ORDER: 'ERR-4013',
  PAYMENT_INVALID_STATUS: 'ERR-4014',
  PAYMENT_INVALID_TOTAL_AMOUNT: 'ERR-4015',
  PAYMENT_EMPTY_ORDER_ITEMS: 'ERR-4016',
  PAYMENT_NOT_CERT_USER: 'ERR-4020',
  CREATION_LIMIT_EXCEEDED: 'ERR-3000',
  CERTIFICATION_UNAUTHORIZED: 'ERR-3012',
} as const;
