export const errorCode = {
  OAUTH_SIGN_IN_NOT_FOUND_USER: 'ERR-2002',
  PAYMENT_NOT_FOUND_ORDER: 'ERR-4012',
  PAYMENT_EXPIRED_ORDER: 'ERR-4013',
  PAYMENT_INVALID_STATUS: 'ERR-4014',
  PAYMENT_INVALID_TOTAL_AMOUNT: 'ERR-4015',
  PAYMENT_EMPTY_ORDER_ITEMS: 'ERR-4016',
} as const;
